Vagrant.configure("2") do |config|

    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    # Configuration de la VM Master
    config.vm.define "bwongS" do |master|
        master.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
        master.vm.hostname = "bwongS"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.provider "virtualbox" do |vb|
            vb.name = "bwongS"
            vb.memory = "2048"
            vb.cpus = 4
        end

        master.vm.provision "shell", path: "scripts/k3s-master.sh"
    end

end
