IOT_BOX = ENV.fetch("IOT_BOX") {
  `uname -m`.strip == "arm64" ? "bento/rockylinux-9" : "generic/centos9s"
}

Vagrant.configure("2") do |config|
    config.vm.box = IOT_BOX
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    config.vm.define "bwongS" do |master|
        master.vm.hostname = "bwongS"
        master.vm.network "private_network",
            ip: "192.168.56.110",
            netmask: "255.255.255.0",
            auto_config: true
        master.vm.provider "virtualbox" do |vb|
            vb.name = "bwongS"
            vb.memory = "2048"
            vb.cpus = 4
        end

        master.vm.provision "shell", path: "scripts/centos-setup.sh"
        master.vm.provision "shell", path: "scripts/k3s-master.sh"
    end
end
