Vagrant.configure("2") do |config|
    # Single-node K3s + 3 apps + ingress on CentOS 7 (42 IoT subject)
    # private_network is attached to eth1 on CentOS/VirtualBox
    config.vm.box = "centos/7"
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    config.vm.define "bwongS" do |master|
        master.vm.hostname = "bwongS"
        master.vm.network "private_network",
            ip: "192.168.56.110",
            netmask: "255.255.255.0",
            auto_config: true
        master.vm.provider "virtualbox" do |vb|
            vb.name = "bwongS"
            vb.memory = "2048"
            vb.cpus = 4
        end

        master.vm.provision "shell", path: "scripts/centos-setup.sh"
        master.vm.provision "shell", path: "scripts/k3s-master.sh"
    end
end
