Vagrant.configure("2") do |config|

    # vboxsf required: the worker reads the master's node token through /vagrant
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    # Configuration de la VM Master
    config.vm.define "p1-server" do |master|
        master.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
        master.vm.hostname = "p1-server"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.provider "virtualbox" do |vb|
            vb.name = "p1-server"
            vb.memory = "1024"
            vb.cpus = 1
        end

        master.vm.provision "shell", path: "scripts/k3s-master.sh"
    end

    #   Configuration de la VM Worker
    config.vm.define "p1-worker" do |worker|
        worker.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
        worker.vm.hostname = "p1-worker"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "virtualbox" do |vb|
            vb.name = "p1-worker"
            vb.memory = "1024"
            vb.cpus = 1
        end

        worker.vm.provision "shell", path: "scripts/k3s-worker.sh", args: ["192.168.56.110"]
    end


end
