Vagrant.configure("2") do |config|

    # Configuration de la VM Master
    config.vm.define "bwongS" do |master|
        master.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
        master.vm.hostname = "bwongS"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.provider "virtualbox" do |vb|
            vb.name = "bwongS"
            vb.memory = "1024"
            vb.cpus = 1
        end

        master.vm.provision "shell", path: "scripts/k3s-master.sh"
    end

    #   Configuration de la VM Worker
    config.vm.define "bwongSW" do |worker|
        worker.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
        worker.vm.hostname = "bwongSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "virtualbox" do |vb|
            vb.name = "bwongSW"
            vb.memory = "1024"
            vb.cpus = 1
        end

        worker.vm.provision "shell", path: "scripts/k3s-worker.sh", args: ["192.168.56.110"]
    end


end