IOT_BOX = ENV.fetch("IOT_BOX") {
  `uname -m`.strip == "arm64" ? "bento/rockylinux-9" : "centos/7"
}

Vagrant.configure("2") do |config|

    config.vm.define "imqandylS" do |host|
        host.vm.box = IOT_BOX
        host.vm.hostname = "imqandylS"
        host.vm.network "private_network",
            ip: "192.168.56.120",
            netmask: "255.255.255.0",
            auto_config: true
        host.vm.provider "virtualbox" do |vb|
            vb.name = "imqandylS"
            vb.memory = "8192"
            vb.cpus = 4
        end

        host.vm.synced_folder "..", "/vagrant", type: "virtualbox"
    end

end
