Vagrant.configure("2") do |config|

    config.vm.define "p3-host" do |host|
        host.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS
        host.vm.hostname = "p3-host"
        host.vm.network "private_network", ip: "192.168.56.120"
        host.vm.provider "virtualbox" do |vb|
            vb.name = "p3-host"
            vb.memory = "4096"
            vb.cpus = 4
        end

        host.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    end

end
